trainLines:
  - name: ICE60
    description: ICE Test
    orderedRailGroups:
      - orderIndex: 1
        name: 10
        parentStation: München Hbf
        departures: 5:00,6:00,7:00,8:00,9:00,9:30,10:00,18:20
      - orderIndex: 2
        name: 1
        parentStation: Ulm
        departures: 5:10,6:10,7:10,8:10,9:10,9:40,10:10,18:30
        arrivalPlatformSound: ''
        arrivalTrainSound: ''
      - orderIndex: 3
        name: 16
        parentStation: Stuttgart Hbf
        departures: final
        arrivalPlatformSound: "minecraft:block.note_block.pling"
        arrivalTrainSound: "minecraft:entity.experience_orb.pickup"