# Max delay in minutes before changing to the next entry. Default 5
departureTimeoutMinutes: 5

# Update the Displays every x ticks. 10 = 2x per second
displayUpdateTicks: 10

# Warning scrollspeed. Default: 1 tick
textScrollSpeedTicks: 1

# Lookahead for entries in minutes. -1 for unlimited
stationLookAheadMinutes: 120
platformLookAheadMinutes: -1

# Maximum minutes in where the arrival trigger may trigger the on_arrival.
arrivalTriggerLookAheadMinutes: 1

# Set the maximum of entries for the station display
stationDisplayMaxEntries: 12

# If true = sends console output if a train triggers a sign
debugSignActions: false

# Announcement settings for the soundboxes
# Category. Can be: MASTER, MUSIC, RECORD, WEATHER, BLOCK, HOSTILE, NEUTRAL, PLAYER, AMBIENT, VOICE
announcementSoundCategory: MASTER
# Radius of the sound
soundBoxDefaultRadius: 24
# Default volume, can be individually changed in SoundBoxes.yml
soundBoxDefaultVolume: 1.0
# Default pitch, can be individually changed in SoundBoxes.yml
soundBoxDefaultPitch: 1.0

# Delay of soundMessages after server start
soundMessagesInitialDelaySeconds: 60