name: Abfahrtstafel
version: 1.0
main: de.tiger.abfahrtstafel.AbfahrtstafelPlugin
api-version: '1.21'
depend: [BKCommonLib, Train_Carts]

commands:
  abfahrtstafel:
    description: Verwaltung der Abfahrtstafeln

permissions:
  abfahrtstafel.admin:
    description: Vollzugriff auf alle Funktionen
    default: op

  abfahrtstafel.warn:
    description: Warnmeldungen anzeigen und verwalten
    default: op

  abfahrtstafel.reload:
    description: Konfiguration neu laden
    default: op